# Generated by Django 6.0.6 on 2026-06-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baskets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "payment_method",
                    models.CharField(default="demo_cash", max_length=40),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("paid", "Paid"), ("cancelled", "Cancelled")],
                        default="paid",
                        max_length=24,
                    ),
                ),
                (
                    "validated_by",
                    models.CharField(default="demo_cashier", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaction",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"],
                        name="checkout_tr_status_88b72a_idx",
                    )
                ],
            },
        ),
    ]
