# Generated by Django 6.0.6 on 2026-06-30 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("baskets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetectionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device_id", models.CharField(max_length=80)),
                ("detected_label", models.CharField(max_length=120)),
                ("confidence", models.DecimalField(decimal_places=2, max_digits=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("needs_confirmation", "Needs confirmation"),
                            ("unknown_product", "Unknown product"),
                            ("low_confidence", "Low confidence"),
                            ("basket_closed", "Basket closed"),
                        ],
                        max_length=32,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "basket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="baskets.basketsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["detected_label"], name="detections__detecte_8c79ad_idx"
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="detections__status_84714f_idx",
                    ),
                ],
            },
        ),
    ]
